image:
  repository: 265766434317.dkr.ecr.us-east-2.amazonaws.com/llt-integration-service
  tag: "latest"
  pullPolicy: Always

service:
  port: 3003
  type: ClusterIP

replicaCount: 1

configmap:
  create: true
  data:
    NODE_ENV: "test"
    PORT: "3003"
    DB_HOST: "pg-shared-postgresql.postgresql.svc.cluster.local"
    DB_PORT: 5432
    POSTGRES_USER: "postgres"
    POSTGRES_DB: "llt_integration"
    REDIS_URL: "redis://redis-cache-master.apps.svc.cluster.local:6379"
    GOOGLE_CALLBACK_URL: "http://k8s-devllt-99044501de-317195572.us-east-2.elb.amazonaws.com/api/v1/integrations/calendar/google/callback"

envFrom:
  - secretRef:
      name: auth-jwt-db
  - secretRef:
      name: ext-api-keys

env: []  # додаткові змінні, якщо треба

ingress:
  enabled: false

livenessProbe:
  enabled: true
  httpGet: { path: /integrations/health, port: http }
  initialDelaySeconds: 10
readinessProbe:
  enabled: true
  httpGet: { path: /integrations/health, port: http }
  initialDelaySeconds: 5

resources:
  requests: { cpu: 200m, memory: 256Mi }
  limits: {}

podSecurityContext: { enabled: true, fsGroup: 1001 }