{{ include "svc.deployment" . }}
---
{{ include "svc.service" . }}
---
{{ include "svc.ingress" . }}
---
{{ include "svc.configmap" . }}
---
{{include "svc.serviceaccount" . }}
---
{{ include "svc.hpa" . }}
