image:
  repository: 265766434317.dkr.ecr.us-east-2.amazonaws.com/llt-trip-service
  tag: "latest"
  pullPolicy: Always

service:
  port: 3000
  type: ClusterIP

replicaCount: 2

configmap:
  create: true
  data:
    NODE_ENV: "test"
    PORT: "3000"
    DB_HOST: "pg-shared-postgresql.postgresql.svc.cluster.local"
    DB_PORT: 5432
    POSTGRES_USER: "postgres"
    POSTGRES_DB: "llt_trip"

envFrom:
  - secretRef:
      name: auth-jwt-db

env: []  # додаткові змінні, якщо треба

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /trip/health
    alb.ingress.kubernetes.io/group.name: dev-llt
  hosts:
    - paths:
      - path: /trip/health
        pathType: Prefix
      - path: /api/v1/trips
        pathType: Prefix
      - path: /api/v1/users
        pathType: Prefix
      - path: /trip/docs
        pathType: Prefix

livenessProbe:
  enabled: true
  httpGet: { path: /trip/health, port: http }
  initialDelaySeconds: 10
readinessProbe:
  enabled: true
  httpGet: { path: /trip/health, port: http }
  initialDelaySeconds: 5

resources:
  requests: { cpu: 200m, memory: 256Mi }
  limits: {}

podSecurityContext: { enabled: true, fsGroup: 1001 }