image:
  repository: 265766434317.dkr.ecr.us-east-2.amazonaws.com/llt-ai-recommender
  tag: "latest"
  pullPolicy: Always

service:
  port: 8000
  type: ClusterIP

replicaCount: 1

configmap:
  create: true
  data:
    NODE_ENV: "test"
    PORT: "8000"
    DB_HOST: "pg-shared-postgresql.postgresql.svc.cluster.local"
    DB_PORT: 5432
    POSTGRES_USER: "postgres"
    POSTGRES_DB: "llt_ai_recommender"
    JWT_ALG: "HS256"
    DEFAULT_LLM_PROVIDER: "openai"
    INTEGRATION_SERVICE_URL: "http://integration-service-integration-service.apps.svc.cluster.local:3003/api/v1/integrations"

envFrom:
  - secretRef:
      name: auth-jwt-db
  - secretRef:
      name: llm-api-keys

env: [] # додаткові змінні, якщо треба

ingress:
  enabled: false

livenessProbe:
  enabled: true
  httpGet: { path: /recommender/health, port: http }
  initialDelaySeconds: 10
readinessProbe:
  enabled: true
  httpGet: { path: /recommender/health, port: http }
  initialDelaySeconds: 5

resources:
  requests: { cpu: 200m, memory: 256Mi }
  limits: {}

podSecurityContext: { enabled: true, fsGroup: 1001 }
