image:
  repository: 265766434317.dkr.ecr.us-east-2.amazonaws.com/llt-auth-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 3000
  type: ClusterIP

replicaCount: 2

configmap:
  create: true
  data:
    NODE_ENV: "test"
    PORT: "3000"
    DB_HOST: "pg-shared-postgresql.postgresql.svc.cluster.local"
    DB_PORT: 5432
    POSTGRES_USER: "postgres"
    POSTGRES_DB: "llt_auth"
    CORS_ORIGIN: "*"
    JWT_ALG: "HS256"
    ACCESS_TOKEN_TTL: "1h"
    REFRESH_TOKEN_TTL: "10d"
    GOOGLE_CLIENT_ID: "812448263301-a2lpffgig4ot2ai7ajm0s5qlsfsumvqi.apps.googleusercontent.com"

envFrom:
  - secretRef:
      name: auth-jwt-db

env: [] # додаткові змінні, якщо треба

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/group.name: dev-llt
  hosts:
    - paths:
      - path: /api/v1/auth
        pathType: Prefix
      - path: /auth/docs
        pathType: Prefix

livenessProbe:
  enabled: true
  httpGet: { path: /health, port: http }
  initialDelaySeconds: 10
readinessProbe:
  enabled: true
  httpGet: { path: /health, port: http }
  initialDelaySeconds: 5

resources:
  requests: { cpu: 200m, memory: 256Mi }
  limits: {}

podSecurityContext: { enabled: true, fsGroup: 1001 }
