{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ default "argocd" .namespace }}
spec:
  project: {{ default "default" .project }}
  source:
    repoURL: {{ .source.repoURL | quote }}
    path: {{ .source.path | quote }}
    targetRevision: {{ .source.targetRevision | quote }}
    {{- if .source.helm }}
    helm:
      {{- if .source.helm.valueFiles }}
      valueFiles:
      {{- range .source.helm.valueFiles }}
        - {{ . | quote }}
      {{- end }}
      {{- end }}
      # {{/* parameters section is commented out by default; uncomment and modify as needed */}}:
      # parameters:
      #   - name: image.tag
      #     value: "sha-1234567"
      # */}}
    {{- end }}
  destination:
    server: {{ default "https://kubernetes.default.svc" .destination.server | quote }}
    namespace: {{ .destination.namespace | quote }}
  syncPolicy:
    {{- if .syncPolicy.automated }}
    automated:
      prune: {{ default true .syncPolicy.automated.prune }}
      selfHeal: {{ default true .syncPolicy.automated.selfHeal }}
    {{- end }}
    {{- if .syncPolicy.syncOptions }}
    syncOptions:
    {{- range .syncPolicy.syncOptions }}
      - {{ . | quote }}
    {{- end }}
    {{- end }}
    {{- if .syncPolicy.retry }}
    retry:
      limit: {{ default 5 .syncPolicy.retry.limit }}
      {{- if .syncPolicy.retry.backoff }}
      backoff:
        duration: {{ default "5s" .syncPolicy.retry.backoff.duration | quote }}
        factor: {{ default 2 .syncPolicy.retry.backoff.factor }}
        maxDuration: {{ default "3m" .syncPolicy.retry.backoff.maxDuration | quote }}
      {{- end }}
    {{- end }}
---
{{- end }}